### ISSUE TITLE
Add NFC plugin from Cordova

### ISSUE THREAD

**Issue by gokr** [evothings/evothings-viewer#19]
Upon "popular request" we should include:

https://github.com/chariotsolutions/phonegap-nfc.git

**Comment by mikaelkindborg** [comment]
Added in this commit: https://github.com/evothings/evothings-viewer/commit/a6d8702c3dbb86aa6e00139b4b736a9b8fa44b01

How do we test the NFC plugin? Do we have an NFC card or emulator?

**Comment by mikaelkindborg** [comment]
Status update:

The NFC plugin is added in in Evothings Viewer 1.4 for Android.

An APK for testing is available here: https://github.com/evothings/evothings-viewer/issues/22#issuecomment-216065997

Testing is needed.

**Comment by mikaelkindborg** [comment]
Plugin still untested, testing is welcome!

**Comment by mikaelkindborg** [comment]
This should work to test scanning for NFC tags.

Paste code in the Workbench Tools window. Select code and click button "Eval Selection". If successful, the data for NFC events should be printed in the log panel.

    nfc.addTagDiscoveredListener(
        function(nfcEvent) {
            hyper.log('Non-NDEF tag discovered: ' + JSON.stringify(nfcEvent))
        },
        function() {
            console.log('Listening for non-NDEF tags')
        },
        function() {
            console.log('Error addTagDiscoveredListener: ' + error)
        })

    nfc.addNdefListener(
        function(nfcEvent) {
            hyper.log('NDEF tag discovered: ' + JSON.stringify(nfcEvent))
        },
        function() {
            console.log('Listening for NDEF tags')
        },
        function() {
            console.log('Error addNdefListener: ' + error)
        })
