### ISSUE TITLE
evothings-viewer build fails

### ISSUE THREAD

**Issue by faytom** [evothings/evothings-viewer#21]
I follow the instruction and the following build error occurs. Please help
The following build commands failed:
	CompileC build/Viewer.build/Debug-iphonesimulator/Viewer.build/Objects-normal/i386/MainViewController.o Viewer/Classes/MainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/feizheng/Desktop/evothings-viewer-master/platforms/ios/cordova/build-debug.xcconfig,-project,Viewer.xcodeproj,ARCHS=i386,-target,Viewer,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/feizheng/Desktop/evothings-viewer-master/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/feizheng/Desktop/evothings-viewer-master/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/feizheng/Desktop/evothings-viewer-master/platforms/ios/cordova/build-debug.xcconfig,-project,Viewer.xcodeproj,ARCHS=i386,-target,Viewer,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/feizheng/Desktop/evothings-viewer-master/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/feizheng/Desktop/evothings-viewer-master/platforms/ios/build/sharedpch

**Comment by mikaelkindborg** [comment]
@faytom Perhaps this is an issue with the Xcode version. Which version are you using? I use Xcode 7.2 at the moment.

**Comment by yaotzin68** [comment]
i had the same error, before i got this:

platforms/ios/Viewer/Classes/AppDelegate.m:128:34: error: no visible @interface for 'UIView' declares the selector 'loadRequest:'
    [self.viewController.webView loadRequest: request];
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~
1 error generated.

Xcode Version 7.3 (7D175)

**Comment by mikaelkindborg** [comment]
@yaotzin68 Which version of Cordova are you using?

**Comment by yaotzin68** [comment]
cordova 6.1.1

**Comment by mikaelkindborg** [comment]
@yaotzin68 Thanks, I am using 5.4.1, will upgrade and test.

**Comment by yaotzin68** [comment]
@mikaelkindborg  hi, how was your testing? can i download again and try?

**Comment by mikaelkindborg** [comment]
@yaotzin68 Sorry not finished with testing yet!

**Comment by mikaelkindborg** [comment]
@yaotzin68 @faytom 

Fixed iOS build problems with Cordova 6, see these commits: 
https://github.com/evothings/evothings-viewer/commit/659aff20f579e02af9055d641b7f6981d1ac22d1
https://github.com/evothings/evothings-viewer/commit/e305b8a7ec8f86e54997c22699ff1a374721fa15
https://github.com/evothings/evothings-viewer/commit/9a8bc60576fbc838c5e0042fac2e8c5a4543ef3a

Please note that plugin cordova-HTTP is updated (fixed build errors), new version is v0.2.2: https://github.com/evothings/cordova-HTTP/releases The reference in the list of plugins in package.json is updated to this version.

**Comment by yaotzin68** [comment]
@mikaelkindborg nice, i will try it thanks

**Comment by mikaelkindborg** [comment]
@yaotzin68 Hi, closing this issue, let me know if I should reopen, if you find any issues.
