### ISSUE TITLE
Nice with cordova.js link already in connect screen's index.html file

### ISSUE THREAD

**Issue by mazekeeper** [evothings/evothings-viewer#8]
Some examples have it, others not. Therefore Eval under tools only works when an example has been loaded. Better have it there too !

**Comment by mikaelkindborg** [comment]
Include of cordova,js added by this commit: https://github.com/mikaelkindborg/evothings-server/commit/b54d442c046b80ff6bb8129cacc6111ff37ed775

Included in this pull request: https://github.com/evothings/evothings-server/pull/46

**Comment by mikaelkindborg** [comment]
Include of cordova.js on the Connect screen has been implemented on the server side.
